# config.yaml

training:
  epochs: 300
  train_batch_size: 8
  val_batch_size: 4
  test_batch_size: 4
  lr: 1e-4             #initial learning rate 
  weight_decay: 1e-5
  dropout: 0.0         # Dropout
  lmbda: 1             # weight of the Cd Loss in the total loss
  delta: 0.1           # hyperparameter of the L1 Clamped Loss
  lmbda_eikonal: 0.1   # hyperparameter of the Eikonal loss
  
scheduler:
  factor: 0.2              
  patience: 10            
  min_lr: 1e-6 

model:
  latent_dim: 128    # dimension of the latent vector 
  hidden_dim: 256    # dimension of hidden layers

data:
  train_path: "/data_split/train_data.h5"
  val_path: "/data_split/val_data.h5"
  test_path: "/data_split/test_data.h5"
  OOD_path: "/data_split/ModelNet40.h5"




